runtime: trtllm
compile_backend: torch-cudagraph
attn_backend: trtllm
max_batch_size: 256
max_seq_len: 8192
enable_chunked_prefill: true
cuda_graph_config:
  max_batch_size: 256
  batch_sizes: [1, 2, 4, 8, 16, 32, 64, 128, 256]
kv_cache_config:
  tokens_per_block: 32
transforms:
  fuse_gemms_mixed_children:
    enabled: true
  match_swiglu_pattern:
    enabled: true
  match_nvfp4_swiglu_pattern:
    enabled: true
  fuse_nvfp4_moe:
    allow_different_input_scales: true
  fuse_nvfp4_swiglu:
    enabled: true
  fuse_swiglu:
    enabled: true
  multi_stream_moe:
    enabled: true
  multi_stream_mla_attn:
    enabled: true
  detect_sharding:
    allreduce_strategy: SYMM_MEM
    shard_all_unprocessed: true
    simple_shard_filter: "lm_head"
  gather_logits_before_lm_head:
    enabled: true
  compile_model:
    piecewise_enabled: true
    piecewise_num_tokens: [256, 512, 1024, 2048, 4096, 8192]
