# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# KV cache transfer config for disaggregated serving.
# Valid backend values include DEFAULT (i.e., NIXL), UCX, and NIXL.
# See examples/disaggregated/README.md for the full disaggregated serving setup.
cache_transceiver_config:
  backend: DEFAULT
# Overlap scheduling is currently unsupported for disaggregated context workers.
disable_overlap_scheduler: true
