# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# Selects the KV-cache transport used to move cache blocks between disaggregated workers.
# Valid backend values include DEFAULT, UCX, and NIXL; see examples/disaggregated/README.md.
cache_transceiver_config:
  backend: DEFAULT
# Overlap scheduling is currently unsupported for disaggregated context workers.
disable_overlap_scheduler: true
