# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate Bazel pytest targets for narrow AutoDeploy H100 manifest entries."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.ci_target_graph.generate import build_manifest

OUTPUT_RELATIVE_PATH = Path("ci/bazel/autodeploy/generated/BUILD.bazel")
_AUTODEPLOY_H100_YAMLS = {
    "tests/integration/test_lists/test-db/l0_dgx_h100.yml",
    "tests/integration/test_lists/test-db/l0_h100.yml",
}
_RUNTIME_DEP = "//tensorrt_llm/_torch/auto_deploy:runtime"
_ACCURACY_DEP = "//tests/integration/defs/accuracy:accuracy_tests"
_PHASE6_METADATA_DEPS = [
    "//:tensorrt_llm_wheel_metadata",
    "//cpp:cuda_kernels_metadata",
    "//cpp:nvinfer_plugin_tensorrt_llm_metadata",
    "//cpp:tensorrt_llm_bindings_metadata",
]
_TRITON_DEP = "//triton_backend:triton_tensorrt_llm_backend"
_GPU_CONSTRAINT_VALUES = {
    "b200": "//platforms/gpu:b200",
    "h100": "//platforms/gpu:h100",
}
_GPU_COUNT_CONSTRAINT_VALUES = {
    1: "//platforms/gpu_count:one",
    4: "//platforms/gpu_count:four",
}


@dataclass(frozen=True)
class BazelPytestCase:
    """Rendered Bazel metadata for one generated pytest selector target."""

    name: str
    selector: str
    pytest_args: list[str]
    tags: list[str]
    target_compatible_with: list[str]
    timeout: str
    deps: list[str]


def select_autodeploy_h100_targets(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    """Select pre-merge AutoDeploy H100 entries from l0_h100 and l0_dgx_h100."""
    targets = manifest.get("targets", [])
    if not isinstance(targets, list):
        return []
    selected = [target for target in targets if _is_autodeploy_h100_target(target)]
    return sorted(selected, key=lambda target: str(target["target_id"]))


def bazel_cases_from_manifest(manifest: dict[str, Any]) -> list[BazelPytestCase]:
    """Convert selected manifest targets into Bazel pytest case metadata."""
    return [
        _case_from_manifest_target(target) for target in select_autodeploy_h100_targets(manifest)
    ]


def build_autodeploy_h100_build(manifest: dict[str, Any]) -> str:
    """Render the generated AutoDeploy H100 BUILD.bazel file."""
    cases = bazel_cases_from_manifest(manifest)
    lines = [
        "# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.",
        "# SPDX-License-Identifier: Apache-2.0",
        "",
        "# Generated by scripts/ci_target_graph/generate_bazel_autodeploy.py; do not edit by hand.",
        "# Source: pre-merge AutoDeploy H100 entries from l0_h100.yml and l0_dgx_h100.yml.",
        "",
        'load("//ci/bazel:defs.bzl", "trtllm_pytest_case")',
        "",
        'package(default_visibility = ["//visibility:public"])',
        "",
    ]

    for case in cases:
        lines.extend(_render_case(case))
        lines.append("")

    lines.extend(_render_suite("autodeploy_h100_1gpu_generated", _cases_with_gpu_count(cases, 1)))
    lines.append("")
    lines.extend(_render_suite("autodeploy_h100_4gpu_generated", _cases_with_gpu_count(cases, 4)))
    lines.append("")
    lines.extend(_render_suite("autodeploy_h100_generated", cases))
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Bazel pytest targets for AutoDeploy H100 manifest entries."
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path.cwd(),
        help="Path to the TensorRT-LLM repository root.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_RELATIVE_PATH,
        help="Generated BUILD.bazel output path, relative to --repo-root unless absolute.",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Write generated BUILD content to stdout instead of --output.",
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    manifest = build_manifest(repo_root)
    build_content = build_autodeploy_h100_build(manifest)

    if args.stdout:
        sys.stdout.write(build_content)
        return 0

    output = args.output
    if not output.is_absolute():
        output = repo_root / output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_content, encoding="utf-8")
    print(f"wrote {output}", file=sys.stderr)
    return 0


def _is_autodeploy_h100_target(target: Any) -> bool:
    if not isinstance(target, dict) or target.get("kind") != "pytest_selector":
        return False

    source = target.get("source")
    constraints = target.get("constraints")
    runtime = target.get("runtime")
    if not isinstance(source, dict) or not isinstance(constraints, dict):
        return False
    if not isinstance(runtime, dict):
        return False

    return (
        source.get("yaml") in _AUTODEPLOY_H100_YAMLS
        and constraints.get("stage") == "pre_merge"
        and runtime.get("backend") == "autodeploy"
        and "h100" in _runtime_gpu_types(runtime)
    )


def _case_from_manifest_target(target: dict[str, Any]) -> BazelPytestCase:
    selector = target["selector"]
    selector_paths = list(selector.get("paths") or [])
    if not selector_paths and selector.get("path"):
        selector_paths = [selector["path"]]
    if not selector_paths:
        selector_paths = [selector["raw"]]

    runtime = target["runtime"]
    pytest_args = selector_paths[1:] + list(selector.get("pytest_args") or [])
    tags = _tags_for_target(target)
    deps = _PHASE6_METADATA_DEPS + [_RUNTIME_DEP]
    if _has_accuracy_path(selector_paths):
        deps.append(_ACCURACY_DEP)
    if "requires:triton" in tags:
        deps.append(_TRITON_DEP)

    return BazelPytestCase(
        name=str(target["target_id"]).split(":", 1)[1],
        selector=selector_paths[0],
        pytest_args=pytest_args,
        tags=tags,
        target_compatible_with=_target_compatible_with(runtime),
        timeout=_bazel_timeout(selector.get("timeout_minutes")),
        deps=_sorted_unique(deps),
    )


def _tags_for_target(target: dict[str, Any]) -> list[str]:
    tags = list(target.get("tags") or [])
    runtime = target.get("runtime")
    if isinstance(runtime, dict):
        tags.extend(_runtime_tags(runtime))
    return _dedupe_preserving_order(tags)


def _target_compatible_with(runtime: dict[str, Any]) -> list[str]:
    constraints = [
        _GPU_CONSTRAINT_VALUES[gpu_type]
        for gpu_type in _runtime_gpu_types(runtime)
        if gpu_type in _GPU_CONSTRAINT_VALUES
    ]
    gpu_count = _runtime_gpu_count(runtime)
    if gpu_count in _GPU_COUNT_CONSTRAINT_VALUES:
        constraints.append(_GPU_COUNT_CONSTRAINT_VALUES[gpu_count])
    return constraints


def _runtime_tags(runtime: dict[str, Any]) -> list[str]:
    tags: list[str] = []
    model_families = _runtime_string_list(runtime.get("model_families"))
    if model_families:
        tags.extend(f"model:{model_family}" for model_family in model_families)
    else:
        tags.append("model:unknown")

    backend = runtime.get("backend")
    if isinstance(backend, str) and backend:
        tags.append(f"backend:{backend}")

    for gpu_type in _runtime_gpu_types(runtime):
        tags.append(f"gpu:{gpu_type}")

    gpu_count = _runtime_gpu_count(runtime)
    if gpu_count is not None:
        tags.append(f"gpu_count:{gpu_count}")

    for requirement in _runtime_string_list(runtime.get("requirements")):
        tags.append(f"requires:{requirement}")

    if runtime.get("metadata_complete") is True:
        tags.append("metadata:runtime_complete")
    else:
        tags.append("metadata:runtime_incomplete")
    return tags


def _runtime_gpu_types(runtime: dict[str, Any]) -> list[str]:
    return _runtime_string_list(runtime.get("gpu_types"))


def _runtime_gpu_count(runtime: dict[str, Any]) -> int | None:
    gpu_count = runtime.get("gpu_count")
    if isinstance(gpu_count, int) and not isinstance(gpu_count, bool):
        return gpu_count
    return None


def _runtime_string_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item) for item in value]


def _bazel_timeout(timeout_minutes: Any) -> str:
    if not isinstance(timeout_minutes, int) or isinstance(timeout_minutes, bool):
        return "long"
    if timeout_minutes <= 1:
        return "short"
    if timeout_minutes <= 5:
        return "moderate"
    if timeout_minutes <= 15:
        return "long"
    return "eternal"


def _has_accuracy_path(selector_paths: list[str]) -> bool:
    return any(
        selector_path.startswith("accuracy/")
        or selector_path.startswith("tests/integration/defs/accuracy/")
        for selector_path in selector_paths
    )


def _cases_with_gpu_count(
    cases: list[BazelPytestCase],
    gpu_count: int,
) -> list[BazelPytestCase]:
    gpu_count_tag = f"gpu_count:{gpu_count}"
    return [case for case in cases if gpu_count_tag in case.tags]


def _render_case(case: BazelPytestCase) -> list[str]:
    lines = [
        "trtllm_pytest_case(",
        f"    name = {_starlark_string(case.name)},",
        f"    selector = {_starlark_string(case.selector)},",
    ]
    lines.extend(_render_attr_list("tags", case.tags))
    lines.extend(_render_attr_list("target_compatible_with", case.target_compatible_with))
    lines.append(f"    timeout = {_starlark_string(case.timeout)},")
    if case.pytest_args:
        lines.extend(_render_attr_list("pytest_args", case.pytest_args))
    lines.extend(_render_attr_list("deps", case.deps))
    lines.append("    manual = True,")
    lines.append(")")
    return lines


def _render_suite(name: str, cases: list[BazelPytestCase]) -> list[str]:
    lines = [
        "test_suite(",
        f"    name = {_starlark_string(name)},",
        '    tags = ["manual"],',
    ]
    lines.extend(_render_attr_list("tests", [f":{case.name}" for case in cases]))
    lines.append(")")
    return lines


def _render_attr_list(name: str, values: list[str]) -> list[str]:
    if not values:
        return [f"    {name} = [],"]

    lines = [f"    {name} = ["]
    for value in values:
        lines.append(f"        {_starlark_string(value)},")
    lines.append("    ],")
    return lines


def _starlark_string(value: str) -> str:
    return json.dumps(value)


def _dedupe_preserving_order(values: list[str]) -> list[str]:
    seen = set()
    deduped = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        deduped.append(value)
    return deduped


def _sorted_unique(values: list[str]) -> list[str]:
    return sorted(set(values))


if __name__ == "__main__":
    raise SystemExit(main())
